### ISSUE TITLE
Error running kitchen list

### ISSUE THREAD

**Issue by DennisDenuto** [neillturner/kitchen-cloudformation#1]
Running kitchen list results in the following error:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'cloudformation' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

cat .kitchen/logs/kitchen.log

```
E, [2016-02-16T16:25:33.628866 #36050] ERROR -- Kitchen: ------Exception-------
E, [2016-02-16T16:25:33.628935 #36050] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2016-02-16T16:25:33.628954 #36050] ERROR -- Kitchen: Message: Could not load the 'cloudformation' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
E, [2016-02-16T16:25:33.628967 #36050] ERROR -- Kitchen: ---Nested Exception---
E, [2016-02-16T16:25:33.628995 #36050] ERROR -- Kitchen: Class: LoadError
E, [2016-02-16T16:25:33.629007 #36050] ERROR -- Kitchen: Message: cannot load such file -- kitchen/driver/cloudformation
E, [2016-02-16T16:25:33.629019 #36050] ERROR -- Kitchen: ------Backtrace-------
E, [2016-02-16T16:25:33.629030 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/driver.rb:50:in `rescue in for_plugin'
E, [2016-02-16T16:25:33.629052 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/driver.rb:40:in `for_plugin'
E, [2016-02-16T16:25:33.629077 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/config.rb:230:in `new_driver'
E, [2016-02-16T16:25:33.629089 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/config.rb:243:in `new_instance'
E, [2016-02-16T16:25:33.629100 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/config.rb:139:in `block in build_instances'
E, [2016-02-16T16:25:33.629112 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/config.rb:138:in `map'
E, [2016-02-16T16:25:33.629134 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/config.rb:138:in `with_index'
E, [2016-02-16T16:25:33.629155 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/config.rb:138:in `build_instances'
E, [2016-02-16T16:25:33.629166 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/config.rb:114:in `instances'
E, [2016-02-16T16:25:33.629177 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command.rb:115:in `filtered_instances'
E, [2016-02-16T16:25:33.629189 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command.rb:145:in `parse_subcommand'
E, [2016-02-16T16:25:33.629200 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command/list.rb:32:in `call'
E, [2016-02-16T16:25:33.629211 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/cli.rb:56:in `perform'
E, [2016-02-16T16:25:33.629225 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/cli.rb:116:in `list'
E, [2016-02-16T16:25:33.629260 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2016-02-16T16:25:33.629283 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2016-02-16T16:25:33.629294 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/cli.rb:321:in `invoke_task'
E, [2016-02-16T16:25:33.629306 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2016-02-16T16:25:33.629327 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2016-02-16T16:25:33.629338 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/bin/kitchen:13:in `block in <top (required)>'
E, [2016-02-16T16:25:33.629356 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/errors.rb:154:in `with_friendly_errors'
E, [2016-02-16T16:25:33.629369 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/bin/kitchen:13:in `<top (required)>'
E, [2016-02-16T16:25:33.629380 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/bin/kitchen:23:in `load'
E, [2016-02-16T16:25:33.629391 #36050] ERROR -- Kitchen: /opt/boxen/rbenv/versions/2.1.2/bin/kitchen:23:in `<main>'
E, [2016-02-16T16:25:33.629402 #36050] ERROR -- Kitchen: ----------------------
```

cat .kitchen.yml

```

---
driver:
        name: cloudformation
        stack_name: mystack

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:
```

gem list

```
artifactory (2.3.2)
awesome_print (1.6.1)
aws-sdk (2.2.16)
aws-sdk-core (2.2.16)
aws-sdk-resources (2.2.16)
aws-sdk-v1 (1.59.1)
bigdecimal (1.2.4)
builder (3.2.2)
bundler (1.11.2, 1.6.3)
chef (12.7.2)
chef-config (12.7.2)
chef-dk (0.10.0)
chef-provisioning (1.6.0)
chef-zero (4.5.0)
cheffish (2.0.1)
coderay (1.1.0)
compat_resource (12.7.1)
cookbook-omnifetch (0.2.2)
dep-selector-libgecode (1.1.0)
dep_selector (1.0.3)
diff-lcs (1.2.5)
erubis (2.7.0)
excon (0.45.4)
extlib (0.9.16)
ffi (1.9.10)
ffi-yajl (2.2.3)
find_a_port (1.0.1)
gssapi (1.2.0)
gyoku (1.3.1)
hashie (3.4.3)
highline (1.7.8)
httpclient (2.7.1)
inifile (2.0.2)
io-console (0.4.2)
ipaddress (0.8.2)
jmespath (1.1.3)
json (1.8.2, 1.8.1)
kitchen-cloudformation (0.0.1)
kitchen-vagrant (0.19.0)
libyajl2 (1.2.0)
little-plugger (1.1.4)
logging (2.0.0)
merb-assets (1.1.3)
merb-core (1.1.3)
merb-helpers (1.1.3)
merb-param-protection (1.1.3)
method_source (0.8.2)
mime-types (1.25.1)
mini_portile2 (2.1.0)
minitar (0.5.4)
minitest (4.7.5)
mixlib-authentication (1.4.0)
mixlib-cli (1.5.0)
mixlib-config (2.2.1)
mixlib-install (0.8.0.alpha.6, 0.7.1)
mixlib-log (1.6.0)
mixlib-shellout (2.2.6)
mixlib-versioning (1.1.0)
molinillo (0.2.3)
multi_json (1.11.2)
net-scp (1.2.1)
net-ssh (3.0.2)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.1)
net-telnet (0.1.1)
nokogiri (1.6.8.rc2)
nori (2.6.0)
ohai (8.10.0)
pact-mock_service (0.4.1)
pact-support (0.3.1)
paint (1.0.1)
plist (3.1.0)
proxifier (1.0.3)
pry (0.10.0)
psych (2.0.5)
rack (1.6.0)
rack-test (0.6.3)
rake (10.1.0)
randexp (0.1.7)
rdoc (4.1.0)
rspec (3.5.0.beta1, 3.2.0)
rspec-core (3.5.0.beta1, 3.2.1)
rspec-expectations (3.5.0.beta1, 3.2.0)
rspec-its (1.2.0)
rspec-mocks (3.5.0.beta1, 3.2.1)
rspec-support (3.5.0.beta1, 3.2.2)
rspec_junit_formatter (0.2.3)
rubyntlm (0.5.3)
safe_yaml (1.0.4)
sass (3.4.13)
semverse (1.2.1)
serverspec (2.29.2)
sfl (2.2)
slop (3.5.0)
solve (2.0.2)
specinfra (2.51.1)
syslog-logger (1.6.8)
systemu (2.6.5)
term-ansicolor (1.3.0)
test-kitchen (1.5.0)
test-unit (2.1.2.0)
thor (0.19.1)
tins (1.3.4)
uuidtools (2.1.5)
vagrant (1.5.0)
webrick (1.3.1)
winrm (1.6.1)
wmi-lite (1.0.0)
```

**Comment by neillturner** [comment]
Test-kitchen seems to be getting confused loading the class, not sure why.  Created new version 0.0.2 that fixes issue. Also may need to put name  of driver is correct case i.e. CloudFormation
not sure exactly when test-kitchen needs the correct case and when all lowercase also works.

``` yaml
---
driver:
  name: CloudFormation
  stack_name: mystack

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:
```

**Comment by DennisDenuto** [comment]
upgraded to 0.0.2 (with case sensitive driver name). that seems to have fixed it. Thanks!
